### ISSUE TITLE
API returns incorrect iBEC file for the device model, breaking the process

### ISSUE THREAD

**Issue by arinc9** [marijuanARM/Inferius#10]
```
arinc9@Arncs-iMac Inferius % python3 inferius.py -d 'iPhone10,6' -i '13.5' -f 'iPhone10,3,iPhone10,6_13.5_17F75_Restore.ipsw' -v
[VERBOSE] Checking for required dependencies...
Finding Firmware bundle for iPhone10,6, 13.5...
[VERBOSE] Firmware bundle exists at: resources/FirmwareBundles/iPhone10,6_13.5_bundle
[VERBOSE] Checking if device is A9...
[VERBOSE] Device is not A9, continuing...
[VERBOSE] iPhone10,3,iPhone10,6_13.5_17F75_Restore.ipsw is a zip archive!
Extracting IPSW at iPhone10,3,iPhone10,6_13.5_17F75_Restore.ipsw. This may take a while, please wait...
[VERBOSE] IPSW extracted to: work/ipsw
IPSW extracted! Verifying bootchain...
[VERBOSE] Firmware/dfu/iBSS.d22.RELEASE.im4p verified!
Traceback (most recent call last):
  File "./inferius.py", line 82, in <module>
    ipsw.verify_bootchain(firmware_bundle, firm_bundle_number, 'yes')
  File "/Volumes/2TB/Inferius/resources/ipsw.py", line 86, in verify_bootchain
    with open(f'work/ipsw/{bootchain_path[x]}', 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'work/ipsw/Firmware/dfu/iBEC.iphone6.RELEASE.im4p'
```
Sounds like an API error from ipsw.me

**Comment by marijuanARM** [comment]
That's more likely an issue with Inferius, I'll look into it.

**Comment by marijuanARM** [comment]
(didn't mean to close yet, haha)

**Comment by NotHereForTheDong** [comment]
Fixed with last commit

**Comment by NotHereForTheDong** [comment]
Fixed with last commit

**Comment by NotHereForTheDong** [comment]
Fixed with last commit
