### ISSUE TITLE
Can't restore

### ISSUE THREAD

**Issue by sparkerfus** [marijuanARM/Inferius#22]
Preparations done! Beginning restore...
[VERBOSE] Sent iBSS
[VERBOSE] Sent iBEC
[VERBOSE] Checking if device is in pwnrecovery...
2020-12-18 16:05:30.311 system_profiler[12067:145435] SPUSBDevice: IOCreatePlugInInterfaceForService failed 0xe00002be
2020-12-18 16:05:30.320 system_profiler[12067:145435] SPUSBDevice: IOCreatePlugInInterfaceForService failed 0xe00002be
[VERBOSE] Device entered pwnrecovery successfully!
[VERBOSE] Device has cellular support, restoring with baseband.
Traceback (most recent call last):
  File "./inferius.py", line 215, in <module>
    restore_ipsw(fresh_ipsw, ipsw_path)
  File "./inferius.py", line 103, in restore_ipsw
    futurerestore = restore.restore(ipsw_path, ipsw.is_cellular(device_identifier), keep_data, downgrade_10, is_verbose)
  File "/Users/sparkerfus/Downloads/Inferius-master/resources/restore.py", line 61, in restore
    if futurerestore.returncode != 0:
UnboundLocalError: local variable 'futurerestore' referenced before assignment

Attempted restore to iOS 11.3 on an iPhone7,1.

**Comment by tolikes** [comment]
Preparations done! Beginning restore...
[VERBOSE] Sent iBSS
[VERBOSE] Sent iBEC
[VERBOSE] Booted iBEC
[VERBOSE] Checking if device is in pwnrecovery...
[VERBOSE] Device entered pwnrecovery successfully!
[VERBOSE] Device has cellular support, restoring with baseband.
Traceback (most recent call last):
  File "/Users/tolikes/Desktop/Inferius-master/./inferius.py", line 215, in <module>
    restore_ipsw(fresh_ipsw, ipsw_path)
  File "/Users/tolikes/Desktop/Inferius-master/./inferius.py", line 103, in restore_ipsw
    futurerestore = restore.restore(ipsw_path, ipsw.is_cellular(device_identifier), keep_data, downgrade_10, is_verbose)
  File "/Users/tolikes/Desktop/Inferius-master/resources/restore.py", line 61, in restore
    if futurerestore.returncode != 0:
UnboundLocalError: local variable 'futurerestore' referenced before assignment

**Comment by marijuanARM** [comment]
fixed with d013db4.
