### ISSUE TITLE
iPhone 7 fail tethered downgrade iOS 14.2 main 

### ISSUE THREAD

**Issue by tolikes** [marijuanARM/Inferius#23]
Preparations done! Beginning restore...
[VERBOSE] Sent iBSS
[VERBOSE] Sent iBEC
[VERBOSE] Booted iBEC
[VERBOSE] Checking if device is in pwnrecovery...
[VERBOSE] Device entered pwnrecovery successfully!
[VERBOSE] Device has cellular support, restoring with baseband.
Traceback (most recent call last):
File "/Users/tolikes/Desktop/Inferius-master/./inferius.py", line 215, in 
restore_ipsw(fresh_ipsw, ipsw_path)
File "/Users/tolikes/Desktop/Inferius-master/./inferius.py", line 103, in restore_ipsw
futurerestore = restore.restore(ipsw_path, ipsw.is_cellular(device_identifier), keep_data, downgrade_10, is_verbose)
File "/Users/tolikes/Desktop/Inferius-master/resources/restore.py", line 61, in restore
if futurerestore.returncode != 0:
UnboundLocalError: local variable 'futurerestore' referenced before assignment

**Comment by marijuanARM** [comment]
fixed with d013db4.
