### ISSUE TITLE
dear, how to do next?

### ISSUE THREAD

**Issue by viccy5022** [marijuanARM/Inferius#56]
gude@gudedeMac-Pro Inferius-master % ./inferius -d iPad4,4 -f /Users/gude/Desktop/Inferius-master/IPSW/iPad_64bit_11.4.1_15G77_Restore_custom.ipsw -r
Restoring custom IPSW
[1] Verifying custom IPSW...
[2] Checking for device in pwned DFU...
[3] Extracting bootchain...
[4] Signing bootchain...
[5] Sending bootchain...
[6] Saving SHSH blobs...
[7] Restoring...
Traceback (most recent call last):
  File "/Users/gude/Desktop/Inferius-master/./inferius", line 150, in <module>
    main()
  File "/Users/gude/Desktop/Inferius-master/./inferius", line 146, in main
    restore_ipsw(api, buildmanifest, custom_ipsw, args.update, tmpdir)
  File "/Users/gude/Desktop/Inferius-master/./inferius", line 87, in restore_ipsw
    restore.restore(ipsw_path, device.baseband, updating)
  File "/Users/gude/Desktop/Inferius-master/utils/restore.py", line 40, in restore
    if 'Done: restoring succeeded!' not in futurerestore.stdout:
TypeError: argument of type 'NoneType' is not iterable

**Comment by vadimszzz** [comment]
@m1stadev I already fixed it in my branch 4 months ago

**Comment by viccy5022** [comment]
> branch

Dear，what is the problem？ And what should I do next. Thanks very much
