### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by D0lcegabbana** [marijuanARM/Inferius#57]
./inferius -d iPhone10,1 -f /Users/cat/Downloads/iPhone_4.7_P3_14.8_18H17_Restore.ipsw -c -b /Users/cat/Downloads/Inferius-master/FirmwareBundles/iPhone10\,1_15.4.1_19E258.bundle  
Creating custom IPSW
[1] Grabbing Firmware Bundle...
Note: Using user provided Firmware Bundle.
[2] Verifying IPSW...
[3] Extracting IPSW...
[4] Patching components...
Traceback (most recent call last):
  File "./inferius", line 150, in <module>
    main()
  File "./inferius", line 141, in main
    custom_ipsw = create_ipsw(api, buildmanifest, ipsw_path, tmpdir, bundle)
  File "./inferius", line 41, in create_ipsw
    bundle.apply_patches(extracted_ipsw)
  File "/Users/cat/Downloads/Inferius-master/utils/bundle.py", line 22, in apply_patches
    bsdiff4.file_patch_inplace(f"{ipsw}/{patch['file']}", f"{self.bundle}/{patch['patch']}")
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bsdiff4/format.py", line 104, in file_patch_inplace
    fo.write(core.patch(data, *read_patch(fi)))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/bsdiff4/format.py", line 40, in read_patch
    assert magic[:7] == MAGIC[:7]
AssertionError
cat@iMac-cat Inferius-master %

**Comment by vadimszzz** [comment]
It’s not inferius error. Your IPSW is damaged

**Comment by vadimszzz** [comment]
Btw bsdiff must be replaced, it is very laggy and causes errors, it doesn’t work
Looks like I must commit again

**Comment by D0lcegabbana** [comment]
Установить другую версию bsdiff?  У меня есть  кстати скомпилированный futurerestore под этот проект могу  скинуть   В твоём форке  инфериуса был вроде неподходящий FR   У меня сейчас есть рабочий . Поделиться ?

**Comment by vadimszzz** [comment]
> Установить другую версию bsdiff? У меня есть кстати скомпилированный futurerestore под этот проект могу скинуть В твоём форке инфериуса был вроде неподходящий FR У меня сейчас есть рабочий . Поделиться ?

Bsdiff говно, он работает очень медленно, нагружает оперативную память на 100% и падает если ipsw больше 2GB. У меня есть форк проекта Inferius где я заменил bsdiff на xdelta3, я уволился из AdGuard и у меня сейчас есть время его выложить. Скоро будет PR.

**Comment by D0lcegabbana** [comment]
> > Установить другую версию bsdiff? У меня есть кстати скомпилированный futurerestore под этот проект могу скинуть В твоём форке инфериуса был вроде неподходящий FR У меня сейчас есть рабочий . Поделиться ?
> 
> Bsdiff говно, он работает очень медленно, нагружает оперативную память на 100% и падает если ipsw больше 2GB. У меня есть форк проекта Inferius где я заменил bsdiff на xdelta3, я уволился из AdGuard и у меня сейчас есть время его выложить. Скоро будет PR.

У меня есть рабочий рэйншторм - аналог инфериуса   Со всеми скомпилированными зависимостями включая futurerestore . Могу тебе скинуть  , может подскажешь что я закосячил , почему при прошивке  в FR  айфон виснет на шестеренке

**Comment by vadimszzz** [comment]
> 

Давай попробую починить

**Comment by D0lcegabbana** [comment]
> 

Напиши в телеграмм , я тебе скинуть проект 
@D0lce_Gabbana
